//const base: string = 'https://nodemy-apis.online';
// const base: string = 'http://localhost:8081';
const base: string = 'https://ourdemy.xyz';
const endpoints = {
    base: base,
    getUsersEndPoint: (page = 1, email = '') => `${base}/users?email=${email}&page=${page}`,
    register: () => `${base}/users`,
    confirmEmail: (userId: string) => `${base}/users/${userId}/verify-activate-token`,
    loginWithNodemy: () => `${base}/users/login-with-nodemy`,
    loginWithGoogle: () => `${base}/users/login-with-google`,
    logout: () => `${base}/users/logout`,
    getAccessToken: () => `${base}/users/get-access-token`,
    getAccountInfo: () => `${base}/users/me`,
    updateNodemyAccount: () => `${base}/users/update-with-nodemy`,
    updateGoogleAccount: () => `${base}/users/update-with-google`,
    changeAccountAvatar: () => `${base}/users/avatar`,
    getHotCourses: () => `${base}/courses/hot`,
    getNewCourses: () => `${base}/courses/new`,
    uploadImageToImgur: () => `https://api.imgur.com/3/image`,
    getTopViewedCourses: () => `${base}/courses/top-viewed`,
    getMostRegisteredCategories: () => `${base}/categories/most-registered`,
    getListCourses: () => `${base}/courses`,
    getAllCategories: () => `${base}/categories`,
    getCourseDetails: (courseId: string) => `${base}/courses/${courseId}`,
    getSections: (courseId: string) => `${base}/sections/${courseId}`,
    getLectures: (sectionId: string) => `${base}/lectures/${sectionId}`,
    buyCourse: (courseId: string) => `${base}/courses/${courseId}/buy`,
    lecture: (lectureId: string) => `${base}/lectures/${lectureId}`,
    getAllRatings: (courseId: string, page: number = 1) => `${base}/ratings/${courseId}?page=${page.toString()}`,
    getOwnRating: (courseId: string) => `${base}/ratings/${courseId}/me`,
    createRating: () => `${base}/ratings`,
    updateRating: (ratingId: string) => `${base}/ratings/${ratingId}`,
    deleteRating: (ratingId: string) => `${base}/ratings/${ratingId}`,
    getOwnListCourses: () => `${base}/courses/me`,
    getCoursesSameCategory: (courseId: string) => `${base}/courses/${courseId}/same-category`,
    getOwnCourse: (courseId: string) => `${base}/courses/me/${courseId}`,
    updateCourse: (courseId: string) => `${base}/courses/${courseId}`,
    addCourse: () => `${base}/courses`,
    deleteCourse: (courseId: string) => `${base}/courses/admin/${courseId}`,
    getTeacherSections: (courseId: string) => `${base}/sections/me/${courseId}`,
    addSection: () => `${base}/sections`,
    updateSection: (sectionId: string) => `${base}/sections/${sectionId}`,
    deleteSection: (sectionId: string) => `${base}/sections/${sectionId}`,
    addLecture: () => `${base}/lectures`,
    deleteLecture: (lectureId: string) => `${base}/lectures/${lectureId}`,
    updateLectureVideo: (lectureId: string) => `${base}/lectures/${lectureId}/video`,
    updateLectureInfo: (lectureId: string) => `${base}/lectures/${lectureId}`,
    upgradeUser: () => `${base}/users/become-teacher`,
    downgradeUser: () => `${base}/users/become-student`,
    banUserEndpoint: () => `${base}/users/ban`,
    unbanUserEndpoint: () => `${base}/users/unban`,
    getCoursesAdminEndpoint: () => `${base}/courses/admin`,
    createCategoryEndpoint: () => `${base}/categories`,
    updateCategoryEndpoint: (id: string) => `${base}/categories/${id}`,
    deleteCatEndpoint: (id: string) => `${base}/categories/${id}`,
    addCourseToWishList: () => `${base}/users/add-course-to-wishlist`,
    getWishlist: () => `${base}/users/wishlist`,
    removeFromWishlist: () => `${base}/users/remove-course-from-wishlist`,
    getOwnSections: (courseId: string) => `${base}/sections/me/${courseId}`,
    getBoughtCourses: () => `${base}/users/bought`,
    loginAdmin: () => `${base}/admin/login`,
    addLectureStaging: () => `${base}/lectures/staging`,
    addLectureConfirm: (lectureId: string) => `${base}/lectures/ready/${lectureId}`,
    getVideoUrl: (lectureId: string) => `${base}/lectures/${lectureId}/video`
};

export default endpoints;
